.PHONY: run
run:
	ampy --port /dev/ttyUSB0 run main.py

.PHONY: put
put:
	ampy --port /dev/ttyUSB0 put main.py

.PHONY: rm
rm:
	ampy --port /dev/ttyUSB0 rm main.py

.PHONY: ls
ls:
	ampy --port /dev/ttyUSB0 ls
